// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type College struct {
	Id                  string `json:"id"`
	ActiveSiteContentId string `json:"activeSiteContentId"`
	Csu                 bool   `json:"csu"`
	Uc                  bool   `json:"uc"`
	AccessibleTextColor bool   `json:"accessibleTextColor"`
}

type HomePageContent struct {
	SiteContentId string `json:"siteContentId"`
	Title         string `json:"title"`
	About         string `json:"about"`
}

type ProgramSummary struct {
	ProgramId            string `json:"programId"`
	Title                string `json:"title"`
	Award                string `json:"award"`
	TruncatedDescription string `json:"truncatedDescription"`
}

type SiteContent struct {
	Id              string `json:"id"`
	CollegeId       string `json:"collegeId"`
	CollegeName     string `json:"collegeName"`
	Year            int    `json:"year"`
	ProgramMapTitle string `json:"programMapTitle"`
	HomePageTitle   string `json:"homePageTitle"`
	ApplyNowUrl     string `json:"applyNowUrl"`
	CollegeLogo     string `json:"collegeLogo"`
	ThemeColor      string `json:"themeColor"`
	Tag             string `json:"tag"`
}
