// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"io"
	"testing"
)

// TestNovelBottlenecksHelpWires smoke-tests that the bottlenecks command
// resolves at runtime and renders --help without error. Catches wiring
// regressions (missing AddCommand, panicking RunE on --help, etc.) before
// review. Always runs — do not delete this test when filling in real cases.
func TestNovelBottlenecksHelpWires(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"bottlenecks", "--help"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("bottlenecks --help error = %v (novel command not wired correctly?)", err)
	}
}

// TestNovelBottlenecksBehavior is the placeholder for table-driven tests of
// the bottlenecks command's actual behavior. Replace the t.Skip with
// real cases — reviewers will flag a shipped t.Skip.
//
// Suggested shape:
//
//	func TestNovelBottlenecksBehavior(t *testing.T) {
//	    cases := []struct {
//	        name  string
//	        input ...
//	        want  ...
//	    }{
//	        // {name: "...", input: ..., want: ...},
//	    }
//	    for _, tc := range cases {
//	        tc := tc
//	        t.Run(tc.name, func(t *testing.T) {
//	            t.Parallel()
//	            // assertions here
//	        })
//	    }
//	}
func TestNovelBottlenecksBehavior(t *testing.T) {
	if got := len(pmMapCourses(nursingMap())); got != 3 {
		t.Fatalf("pmMapCourses count = %d, want 3 COURSE entries for bottleneck aggregation", got)
	}
}
