// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCollegesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "colleges",
		Short:       "California Community Colleges in the ProgramMapper registry",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCollegesGetCmd(flags))
	cmd.AddCommand(newCollegesListCmd(flags))
	cmd.AddCommand(newCollegesResolveCmd(flags))
	return cmd
}
