// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"io"
	"testing"
)

// TestNovelCourseProgramsHelpWires smoke-tests that the course-programs command
// resolves at runtime and renders --help without error. Catches wiring
// regressions (missing AddCommand, panicking RunE on --help, etc.) before
// review. Always runs — do not delete this test when filling in real cases.
func TestNovelCourseProgramsHelpWires(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"course-programs", "--help"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("course-programs --help error = %v (novel command not wired correctly?)", err)
	}
}

// TestNovelCourseProgramsBehavior is the placeholder for table-driven tests of
// the course-programs command's actual behavior. Replace the t.Skip with
// real cases — reviewers will flag a shipped t.Skip.
//
// Suggested shape:
//
//	func TestNovelCourseProgramsBehavior(t *testing.T) {
//	    cases := []struct {
//	        name  string
//	        input ...
//	        want  ...
//	    }{
//	        // {name: "...", input: ..., want: ...},
//	    }
//	    for _, tc := range cases {
//	        tc := tc
//	        t.Run(tc.name, func(t *testing.T) {
//	            t.Parallel()
//	            // assertions here
//	        })
//	    }
//	}
func TestNovelCourseProgramsBehavior(t *testing.T) {
	if _, ok := pmMapCourses(nursingMap())["NURSING 090"]; !ok {
		t.Fatal("pmMapCourses missing NURSING 090 for course-programs reverse lookup")
	}
}
