// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProgramMapsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "program-maps",
		Short:       "Semester-by-semester course plans for a program pathway",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProgramMapsGetCmd(flags))
	cmd.AddCommand(newProgramMapsLinkedCmd(flags))
	return cmd
}
