// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProgramsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "programs",
		Short:       "Degrees and certificates offered at a college",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProgramsGetCmd(flags))
	cmd.AddCommand(newProgramsLinkedCmd(flags))
	cmd.AddCommand(newProgramsNewerYearLinkCmd(flags))
	cmd.AddCommand(newProgramsPathwaysCmd(flags))
	cmd.AddCommand(newProgramsPriorYearsCmd(flags))
	cmd.AddCommand(newProgramsSearchCmd(flags))
	return cmd
}
