// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSiteContentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "site-contents",
		Short:       "Per-college, per-year catalog config (one site-content per college-year)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSiteContentsGetCmd(flags))
	cmd.AddCommand(newSiteContentsHomeCmd(flags))
	return cmd
}
